config:
  trino:
    url: jdbc:trino://${TRINO_HOST}:${TRINO_PORT}
    original-catalog: ${TRINO_ORIGINAL_CATALOG}
    de-identified-catalog: ${TRINO_DE_IDENTIFIED_CATALOG}
    user: ${TRINO_DEFAULT_USER}
  db:
    prefix: project_
    postfix: _research
  jwks:
    url: ${JWK_URL}

server:
  port: 3030
