app:
  jwk:
    url: ${JWK_URL:http://127.0.0.1:3567/recipe/jwt/jwks}
  storage-type: ${STORAGE_TYPE:GCP}
  platform:
    url: ${PLATFORM_URL:http://127.0.0.1:8080}

  signed-url:
    duration: ${SIGNED_URL_DURATION:60}
  gcp:
    project-id: ${GCP_PROJECT_ID}
    bucket: ${GCP_BUCKET_NAME}
  aws:
    region: ${AWS_REGION}
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    bucket: ${AWS_BUCKET_NAME}
  azure:
    account-name: ${AZURE_ACCOUNT_NAME}
    account-key: ${AZURE_ACCOUNT_KEY}
    container-name: ${AZURE_CONTAINER_NAME}
