openapi: 3.0.0
info:
  version: 0.9.0
  title: Cloud Storage Service
paths:
  /cloud-storage/projects/{projectId}/upload-url:
    get:
      summary: Get signed-url for uploading object file
      description: |
        Get signed-url for uploading the given object name.
        You need to call the returned signed-url with "PUT" http method and file as body.
      tags:
        - Object
      parameters:
        - name: projectId
          description: The id of the project to retrieve
          in: path
          required: true
          schema:
            type: integer
        - name: object_name
          description: The name of the object to upload
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                format: url
                example: https://example.url/ex?ex=e
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cloud-storage/projects/{projectId}/download:
    get:
      summary: Download object file
      description: |
        Download object file. It retrieves object file from the given projectId folder.
      tags:
        - Object
      parameters:
        - name: projectId
          description: The id of the project to retrieve
          in: path
          required: true
          schema:
            type: integer
        - name: object_name
          description: The name of the object to download
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The operation was successful. It includes a binary string body.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
                example: (binary string)
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cloud-storage/projects/{projectId}/download-url:
    get:
      summary: Get signed-url for downloading object file
      description: |
        Get signed-url for downloading the given object name.
        You need to call the returned signed-url with "GET" method.
      tags:
        - Object
      parameters:
        - name: projectId
          description: The id of the project to retrieve
          in: path
          required: true
          schema:
            type: integer
        - name: object_name
          description: The name of the object to upload
          in: query
          required: true
          schema:
            type: string
        - name: url_duration
          description: The name of the object to download
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                format: url
                example: https://example.url/ex?ex=e
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cloud-storage/projects/{projectId}/list:
    get:
      summary: List objects
      description: |
        List objects' attribute(name & size). It retrieves objects from the given path.
      tags:
        - Object
      parameters:
        - name: projectId
          description: The id of the project to retrieve
          in: path
          required: true
          schema:
            type: integer
        - name: path
          description: The path where a user wants to retrieve
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The operation was successful.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ObjectInfo"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cloud-storage/projects/{projectId}/delete:
    delete:
      summary: Delete object file
      description: |
        Delete object file. It deletes object file from the given projectId folder.
      tags:
        - Object
      parameters:
        - name: projectId
          description: The id of the project to retrieve
          in: path
          required: true
          schema:
            type: integer
        - name: object_name
          description: The name of the object to download
          in: query
          required: true
          schema:
            type: string
      responses:
        "204":
          description: |
            The operation was successful, so redirect to signed-url.
            Without automatic redirection, you will get 307 as signed-url in Location header.
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    ObjectInfo:
      required:
        - name
        - size
      properties:
        name:
          type: string
        size:
          type: integer
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: [ ]
