name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build account service
      run:  |
          chmod +x gradlew
          ./gradlew :account-service:build -x detekt

    - name: Build platform service
      run:  |
          chmod +x gradlew
          ./gradlew :platform:build -x detekt

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push account service
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./account-service
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/account-service:latest

    - name: Build and push platform
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./platform
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/platform:latest